server.port=8080
spring.application.name=bm
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.hibernate.ddl-auto=update
jwt.secret=04f470a86405506c48a69e16b465238c54ebdf477ad3f70925124f53c2b49b4e
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
cors.frontend=http://localhost:3000
